### ISSUE TITLE
Edit icon throwing exception: Failed to find GeneratedAppGlideModule.

### ISSUE THREAD

**Issue by abdullah432** [koiralapankaj7/drishya_picker#5]
When I click on the edit icon. I'm getting the following error:

```
W/Glide   (32471): Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency on com.github.bumptech.glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored
E/CameraCaptureSession(32471): Session 0: Exception while stopping repeating: 
E/CameraCaptureSession(32471): android.hardware.camera2.CameraAccessException: CAMERA_ERROR (3): The camera device has encountered a serious error
E/CameraCaptureSession(32471):  at android.hardware.camera2.impl.CameraDeviceImpl.checkIfCameraClosedOrInError(CameraDeviceImpl.java:2321)
E/CameraCaptureSession(32471):  at android.hardware.camera2.impl.CameraDeviceImpl.stopRepeating(CameraDeviceImpl.java:1270)
E/CameraCaptureSession(32471):  at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:579)
E/CameraCaptureSession(32471):  at io.flutter.plugins.camera.Camera.closeCaptureSession(Camera.java:1171)
E/CameraCaptureSession(32471):  at io.flutter.plugins.camera.Camera.close(Camera.java:1177)
E/CameraCaptureSession(32471):  at io.flutter.plugins.camera.Camera$1.onError(Camera.java:252)
E/CameraCaptureSession(32471):  at android.hardware.camera2.impl.CameraDeviceImpl.notifyError(CameraDeviceImpl.java:1719)
E/CameraCaptureSession(32471):  at android.hardware.camera2.impl.CameraDeviceImpl.lambda$oDs27OTfKFfK18rUW2nQxxkPdV0(Unknown Source:0)
E/CameraCaptureSession(32471):  at android.hardware.camera2.impl.-$$Lambda$CameraDeviceImpl$oDs27OTfKFfK18rUW2nQxxkPdV0.accept(Unknown Source:8)
E/CameraCaptureSession(32471):  at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:278)
E/CameraCaptureSession(32471):  at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:201)
E/CameraCaptureSession(32471):  at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:97)
E/CameraCaptureSession(32471):  at android.os.Handler.handleCallback(Handler.java:938)
E/CameraCaptureSession(32471):  at android.os.Handler.dispatchMessage(Handler.java:99)
E/CameraCaptureSession(32471):  at android.os.Looper.loop(Looper.java:236)
E/CameraCaptureSession(32471):  at android.app.ActivityThread.main(ActivityThread.java:8047)
E/CameraCaptureSession(32471):  at java.lang.reflect.Method.invoke(Native Method)
E/CameraCaptureSession(32471):  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
E/CameraCaptureSession(32471):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
W/BpBinder(32471): Slow Binder: BpBinder transact took 415ms, interface=android.hardware.camera2.ICameraDeviceUser, code=1 oneway=false
```

[I think here is the solution too.](https://stackoverflow.com/a/49934146/9758506)

Please fix this issue. Thanks

**Comment by koiralapankajgit** [comment]
wait for few days new version is landing soon :)

**Comment by abdullah432** [comment]
I checked the new version, nice work but the edit feature is still not working.

Device Name: Redmi Note 10
Android version: 11

**Comment by koiralapankaj7** [comment]
I forgot to mention that edit feature is not implemented yet. I will update in next version 🙂 .

**Comment by abdullah432** [comment]
Awesome, should I expect it in few days or it will take time?

**Comment by koiralapankaj7** [comment]
Add this to your android -> app -> build.gradle 

```
dependencies {
    ...
    implementation 'com.github.bumptech.glide:glide:4.11.0'
    kapt 'com.github.bumptech.glide:compiler:4.11.0'
}
```

**Comment by abdullah432** [comment]
Getting following issue, after including above lines.

```
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Build file '/.../.../.../.../android/app/build.gradle' line: 64
                                                                        
* What went wrong:                                                      
A problem occurred evaluating project ':app'.                           
> Could not find method kapt() for arguments [com.github.bumptech.glide:compiler:4.12.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

**Comment by koiralapankaj7** [comment]
> Awesome, should I expect it in few days or it will take time?

This might take time. I have a busy schedule :)

**Comment by koiralapankaj7** [comment]
Edit feature is implemented and regarding the glide issue please read the documentation.

**Comment by abdullah432** [comment]
Now it's not throwing any issue but in android when we add emoji or text into a picture. It only returns the image without the emojis and text.

**Comment by hortigado** [comment]
This error was generated for me by another library installed to choose images, I deleted it, I did `flutter clean` and it worked
